### ISSUE TITLE
php artisan migrate [No such file or directory]

### ISSUE THREAD

**Issue by zarEclEC** [cent89/segresta#1]
php artisan migrate

> In Connection.php line 664:                                                                                                                                  
>   SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = segresta and table_name = migrations)  
>                                                                                                                                                       
> 
> In PDOConnection.php line 50:                                             
>   SQLSTATE[HY000] [2002] Connection refused  
>                                              
> 
> In PDOConnection.php line 46:                                   
>   SQLSTATE[HY000] [2002] Connection refused  

Mi da questo errore, che vuol dire?

**Comment by cent89** [comment]
Ciao, sembra che tu abbia messo delle credenziali sbagliate nel file .env.
Verifica che l'utente creato abbia i permessi di lettura/scrittura sul rispettivo database.

```
CREATE DATABASE segresta DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE USER 'segresta'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON segresta.* TO 'segresta'@'localhost';
```
Dopo aver aggiornato il file .env, lancia un 
`php artisan config:cache`

**Comment by zarEclEC** [comment]
php artisan migrate
```
In Connection.php line 664:                                                                                                                                                 
  SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema = segresta and table_name = migrations)  
                                                                                                                                                             
In PDOConnection.php line 50:                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    
In PDOConnection.php line 46:                                                  
  SQLSTATE[HY000] [2002] No such file or directory  
```
                                                    
Mando qui il mio file .env
```
APP_ENV=local
APP_KEY=
APP_DEBUG=false
APP_LOG_LEVEL=debug
APP_URL=http://localhost/segresta
APP_NAME='Segresta 2.0'

SESSION_NAME_ORATORIO=session_oratorio
OWNER_MAIL=armellini.federico@gmail.com

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=segresta
DB_USERNAME=segresta
DB_PASSWORD=password

BROADCAST_DRIVER=log
CACHE_DRIVER=array
SESSION_DRIVER=file
QUEUE_DRIVER=sync

MAIL_DRIVER=mailgun

```
Ho eseguito i tuoi comandi SQL, cosa mi manca?

**Comment by zarEclEC** [comment]
Ho risolto seguende le risposte di questo link
https://stackoverflow.com/questions/22188026/sqlstatehy000-2002-no-such-file-or-directory
Ho sia aggiunto una riga al file database.php (sotto la cartella config), rendendo così la configurazione di mysql 

```
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => 'innodb',
            'unix_socket' => '/opt/lampp/var/mysql/mysql.sock',
        ],

```


E sia facendo 
```
sudo mkdir /var/mysql
cd /var/mysql
sudo ln -s /opt/lampp/var/mysql/mysql.sock
```

Non so quale delle due abbia funzionato, ma facendo 
`php artisan config:cache`
Dopo ha funzionato il migrate

(E' successo però un altro errore, che trattiamo in un altro issue  https://github.com/cent89/segresta/issues/2 , questo chiude)
